language: java
branches:
  only:
  - master
  - develop
env:
  global:
  - secure: ZAOkBVMT6iGXUVcygdRRBT7G211JC0FctVNZbM9Ue0jrBDd+P+pZF/0fKzHQ67EmVZSq5i9J6gNCe5PvdU1bOClE0qNwfMkUD4BY5Bxv99rUHhgpG43Zk4hs0CgSeWRCC7mH93eKxiHrgurxpEaR9JofhGFHOdAezanAxx6Ltrc=
  - secure: H0iKHa2c41Wek38Xpwn5nZIzY57fBZYVxOhwX6l10K1PcboBrH8kMt+M/G2aJtoXEmUb/azKxoGfpfX0ISIq+4NUvljCzRmc0jScoEzoXOIS2y3pzdvoMxR8UtlpFCIT4lSMWDS1s6Gsgh5fUdAUth//30Iymogtwixfv/HZ31g=
  - secure: IDtJYnOHihmykuPhuMSIW6VYO7DQzdMEsG8vvIBt/dHZ0g4mCaHMZ0yfzU1Snqh4CmNJbBg07dwTDFoWpZxakd8rS/iacJ4Ii6rxNJiry0GQP5pBRkjNscaIetHCQm+wO1hEcFrEC/aCbEYhdNOwlN46rESsKpAXReQIiM2ytRk=
  - secure: GQJUQMetUjOEenCFz0jZYH/9nHdpHOft2aRFBTzfC+ZHXq+ZgIDQIAMfx8ISs1mDEF5fCq2JMHIIMK5Ya4AFGgZreXf3AA8QLffhTTWST1fKUiN5NuvM6R2Hatttnujq8DgpbvwRgzh+F+nAJrv+kyYILkiDiw3vi4WFCRyzdKY=
  - secure: BxthWM9clClMbRIbqHt1+RtVg7u7JCtRDZfNhpq1ZQz9KnagurHH5CGDRbt/KRtb/OQHDulUPkvJP8xJUB/Len0H3eemYAgBXJAMY0VKxT+yYTaSpfF/rVcu6UvqNgxC5Ro9FEwXePFZzUiyUWO8wYhJEwN0U35MtcNJ0ai/CSY=
  - secure: KZE3iJkrmivXjP1iDMRDJUVlOQOwg7bbXjBSGQc43mJtkXfWn4I3ccWZefQ66ZeGR75plVjGI6vXsIAKdIW+x+Vvz/ggla9QFftija6hdWqXwniPYenhkS7I0CXMkRnBlcuZwQCxgHcNgKPRcf9uKZPeZXWHlq9iTMg/4x58nb8=
before_install:
- chmod a+x ./deploy.sh
script:
- mvn clean test --settings settings.xml
after_success:
- echo "BRANCH: $TRAVIS_BRANCH"
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./deploy.sh ; fi
